# 批量大小
batch_size: 10
# 训练轮数
epoch: 100

# 音频序列最大长度
max_audio_len: 1000
# 音频对应的中文序列最大长度
max_tgt_len: 40
# 嵌入的维度
embedding_dim: 81
# 隐藏层维度
hidden_dim: 128
# 输出的维度
output_dim: 3507

# 模型名称
Torch_MODEL_NAME: "model.pkl"

# mfcc 特征
sample_rate: 16000
window_size: 0.01
window_stride: 0.01
window: "hamming"

# 训练数据的路径
DATA_PATH: data/input
# 模型保存的路径
MODEL_PATH: demos/data/output/model
# 训练log的输出路径
LOG_PATH: data/output/logs
# Words.json路径
WORDS_PATH: data/input/words.json
# label Path
DEV_PATH: data/input/dev.csv
